#!/bin/bash

# Copyright (c) 2017 Kinsey Favre.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

print_stars()
{
    echo -en "\e[31m"
    for ((i=0; i<80; i++)); do
        echo -n "*"
    done
    echo -en "\e[0m"
    # print final newline
    echo
}

print_stars
echo -e "\e[01;31mQuotation from Chairman Mao of the Day:"
echo -en "\e[01;33m"
fortune FORTUNE_FILE
echo -en "\e[0m"
print_stars
